dist: bionic
language: go
go:
  - 1.12.x

git:
  depth: 1

install: true

script:
  - make test
  - make lintcheck

deploy:
  - provider: script
    script: make release
    skip_cleanup: true
    on:
      branch: master
